Первая учебная работа
Anya-Vasilyeva/s-chistogo-lista pull request #1
Opened 2023-10-09 14:14 UTC by Anya-Vasilyeva

Отправляю на ревью. 
Подскажите, пожалуйста, почему в автотестах мой макет выглядит не так, как при проверке через PerfectPixel - здесь все сходится, а в скрине от автотестов все уезжает пикселей на 20 (в cover текст заголовка как будто разъезжается, а от этого блока уже весь остальной макет тоже едет). Буду признательна за ответ.

2023-10-09 14:43 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Доброго времени суток. У вас получилась хорошая работа!

_ Что понравилось:_

- похоже на макет
- Хорошее форматирование документа
- хорошие стили
- используется семантика
- Используются списки


_Что необходимо исправить:_

- **Все комментарии  с пометкой "Нужно исправить" в коде**




_Что можно улучшить:_

- Все комментарии "Можно лучше"

- Селекторы в файле стилей должны располагаться в порядке их появления в html

- В любом месте в файлах CSS в проекте(кроме самого CSS файла подключения шрифтов, где указывается только название подключаемого шрифта), где указано свойство  `font-family`  помимо основного шрифта так же должен быть указан альтернативный шрифт и тип засечек. Это делается для того, что если по каким-то причинами основной шрифт не загрузится, то внешний вид страницы не будет изменен очень сильно.  Порядок написания шрифтов: Основной шрифт, [Веб-безопасный альтернативный шрифт(по ссылке список этих шрифтов)](https://www.cssfontstack.com/), Тип засечек. Пример ` font-family: Inter, Arial, sans-serif; ` 

- Желательно использовать все классы по БЭМ. 
  - https://ru.bem.info/methodology/quick-start/
  - Проверить ошибки БЭМ можно на  https://nglazov.github.io/bem-validator-page/
  - струтуру можно проверить на https://yoksel.github.io/html-tree/

- Можно использовать атрибуты `target="_blank"` для ссылок на сторонние ресурсы для того чтобы пользователю не приходилось заново открывать сайт проекта
- Для более точной корректировки размеров текстов и расстояний между элементами можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) для Chrome 


**Напоминание:** После выполнения всех критических замечаний работа будет принята. Предложения по улучшению выполняются по желанию.

Желаю успеха!

2023-10-09 14:43 UTC, Avaakum commented on styles/style.css
> +  font-family: 'Inter', 'Arial', sans-serif;
---

**Отлично:**

Корректный шрифт и альтернативы

2023-10-09 14:43 UTC, Avaakum commented on styles/style.css
> +  font-family: 'EB Garamond', 'Times New Roman', serif;
---

**Отлично:**

Корректный шрифт и альтернативы

2023-10-09 14:43 UTC, Avaakum commented on index.html
> +    <a href="">
---

**Отлично:**

Логотип должен быть ссылкой без атрибута href(что бы по ссылке не было перехода) в соответствии с уроком "рекомендации к проекту" для улучшения семантики страницы.

2023-10-09 14:43 UTC, Avaakum commented on index.html
> +  <link rel="stylesheet" href="fonts/fonts.css">
---

**Отлично:**

Правильный порядок подключения стилей. Шрифты должны быть подключены первыми, потом общие стили(сброс), потом кастомные. При таком порядке подключении шрифты могут быть использованы в двух последующих файлах.  А так же сброс стилей должен быть до подключения своих стилей из-за специфики CSS, чтобы `global.css` не переопределил никаких наших стилей.

2023-10-09 14:43 UTC, Avaakum commented on index.html
> +        <li class="header__menu-item">
---

**Отлично:**

Отличная семантика и структура

2023-10-09 14:43 UTC, Avaakum commented on index.html
> +        <h4 class="intro__title">
- Уровень заголовка не соответствует структуре страницы. Это  заголовок секции, по структуре заголовков тут будет h2


---


- Про заголовки и подзаголовки на примере другой страницы с секциями, хэдером, и футером: у нас есть **один заголовок h1 на странице**, в каждой секции есть свой заголовок h2, если там есть другие элементы с заголовками ниже по иерархии, то они будут h3. Если например в секции был бы заголовок h2 и подзаголовок h3, то элементы с заголовками ниже по иерархии в этой же секции были бы уже h4.

2023-10-09 14:43 UTC, Avaakum commented on index.html
> +        <time datetime="2021-10-12" class="intro__date">
---

**Отлично:**

Отличная семантика

2023-10-09 14:43 UTC, Avaakum commented on index.html
> +          <a class="header__menu-item_active">
- У всех ссылок на странице, кроме логотипа в хедере(там тег ссылки нужен только для улучшения семантики, без перехода по ссылке) должен быть атрибут href, или они будут неактивны. Если адресов ссылок пока нет, то можно поставить в значение например ` #0 `

2023-10-09 14:43 UTC, Avaakum commented on styles/style.css
> +  border-top: 1px solid #fee42a ;
Лишние пробелы перед ;

2023-10-09 14:43 UTC, Avaakum commented on index.html
> +      <section class="intro__heading">
- Основные блоки между header и footer мы делим на теги section для улучшения семантики страницы и лучшего восприятия ее поисковыми машинами. Внутри секций используйте div

2023-10-09 14:43 UTC, Avaakum commented on index.html
> +        <section class="intro__main-text">
- Основные блоки между header и footer мы делим на теги section для улучшения семантики страницы и лучшего восприятия ее поисковыми машинами. Внутри секций используйте div

2023-10-09 14:43 UTC, Avaakum commented on index.html
> +      <ul class="content-section__list">
---

**Отлично:**

Отлично, использован список для повторяющихся элементов

2023-10-09 14:43 UTC, Avaakum commented on index.html
> +              <h3 class="card__author-name">
Тут  и далее в карточках это не заголовок, используйте тег p

2023-10-09 14:43 UTC, Avaakum commented on index.html
> +              <h4 class="card-title">
- Уровень заголовка не соответствует структуре страницы. По структуре тут и далее будет h3

2023-10-09 14:46 UTC, Avaakum commented
> Отправляю на ревью. Подскажите, пожалуйста, почему в автотестах мой макет выглядит не так, как при проверке через PerfectPixel - здесь все сходится, а в скрине от автотестов все уезжает пикселей на 20 (в cover текст заголовка как будто разъезжается, а от этого блока уже весь остальной макет тоже едет). Буду признательна за ответ.

Ничего страшного, видимо какое-то расхождения из-за способа вёрстки. В автотестах такое может быть. По наложению картинки через  браузер у вас всё выглядит отлично. 👍🏻

2023-10-09 19:32 UTC, Anya-Vasilyeva commented
> > Отправляю на ревью. Подскажите, пожалуйста, почему в автотестах мой макет выглядит не так, как при проверке через PerfectPixel - здесь все сходится, а в скрине от автотестов все уезжает пикселей на 20 (в cover текст заголовка как будто разъезжается, а от этого блока уже весь остальной макет тоже едет). Буду признательна за ответ.
> 
> Ничего страшного, видимо какое-то расхождения из-за способа вёрстки. В автотестах такое может быть. По наложению картинки через браузер у вас всё выглядит отлично. 👍🏻

Спасибо за комментарии! Поправила. Я правильно сделала, что обновила файлы здесь или надо было создать новую ветку и новый pull request?

2023-10-10 11:54 UTC, Avaakum commented
Развернуть общий комментарий ⬇︎

Здравствуйте! Рад вам сообщить, что ваша работа принята. Сейчас страничка выглядит прекрасно, всё работает отлично. Отличная семантика и структура. Желаю вам удачи в следующих спринтах и проектах! 

Ссылки:

- Можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`. Но если страница с адаптацией, то всегда стоит проверять как текст с пробелами выглядит на всех ширинах.
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- [Ссылка про подгрузку шрифтов](https://only-to-top.ru/blog/tools/2019-03-13-nastrojte-pokaz-vsego-teksta-vo-vremya-zagruzki-veb-shriftov.html) 
- Для более точной корректировки размеров текстов и расстояний между элементами можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) для Chrome 



Несколько  ссылок на материал по теме нативных CSS переменных от авторов практикума:

- [1 часть](https://tproger.ru/articles/custom-properties-in-css-part-1/)

- [2 часть](https://tproger.ru/articles/custom-properties-in-css-part-2/)

- [3 часть](https://tproger.ru/articles/custom-properties-in-css-part-3/)

2023-10-10 11:54 UTC, Avaakum approved these changes
Развернуть общий комментарий ⬇︎

Здравствуйте! Рад вам сообщить, что ваша работа принята. Сейчас страничка выглядит прекрасно, всё работает отлично. Отличная семантика и структура. Желаю вам удачи в следующих спринтах и проектах! 

Ссылки:

- Можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`. Но если страница с адаптацией, то всегда стоит проверять как текст с пробелами выглядит на всех ширинах.
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- [Ссылка про подгрузку шрифтов](https://only-to-top.ru/blog/tools/2019-03-13-nastrojte-pokaz-vsego-teksta-vo-vremya-zagruzki-veb-shriftov.html) 
- Для более точной корректировки размеров текстов и расстояний между элементами можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) для Chrome 



Несколько  ссылок на материал по теме нативных CSS переменных от авторов практикума:

- [1 часть](https://tproger.ru/articles/custom-properties-in-css-part-1/)

- [2 часть](https://tproger.ru/articles/custom-properties-in-css-part-2/)

- [3 часть](https://tproger.ru/articles/custom-properties-in-css-part-3/)

2023-10-10 11:55 UTC, Avaakum commented
> > > Отправляю на ревью. Подскажите, пожалуйста, почему в автотестах мой макет выглядит не так, как при проверке через PerfectPixel - здесь все сходится, а в скрине от автотестов все уезжает пикселей на 20 (в cover текст заголовка как будто разъезжается, а от этого блока уже весь остальной макет тоже едет). Буду признательна за ответ.
> > 
> > 
> > Ничего страшного, видимо какое-то расхождения из-за способа вёрстки. В автотестах такое может быть. По наложению картинки через браузер у вас всё выглядит отлично. 👍🏻
> 
> Спасибо за комментарии! Поправила. Я правильно сделала, что обновила файлы здесь или надо было создать новую ветку и новый pull request?

Да, всё правильно на этом курсе всё отправляется в одну  ветку и пулреквест 😎

2023-10-10 12:00 UTC, Anya-Vasilyeva commented
Спасибо большое за комментарии и массу полезной инфы!

2023-10-10 12:01 UTC, merged